[package]
name = "nvvm"
version = "0.1.0"
authors = ["Riccardo D'Ambrosio <rdambrosio016@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "High level bindings to libnvvm"

[build-dependencies]
find_cuda_helper = { version = "0.1", path = "../find_cuda_helper" }
